# Sử dụng Image chính thức từ Apache
FROM apache/hive:3.1.3

USER root

# 1. Tải PostgreSQL JDBC Driver để kết nối với DB của Airflow
ADD https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /opt/hive/lib/

# THÊM MỚI: Tải bộ đôi thư viện AWS SDK để HMS nói chuyện được với MinIO (S3)
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.1.0/hadoop-aws-3.1.0.jar /opt/hive/lib/
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/aws-java-sdk-bundle-1.11.271.jar /opt/hive/lib/

RUN chmod 644 /opt/hive/lib/postgresql-42.6.0.jar /opt/hive/lib/hadoop-aws-3.1.0.jar /opt/hive/lib/aws-java-sdk-bundle-1.11.271.jar

# 2. Sinh tự động file cấu hình (hive-site.xml)
RUN echo '<configuration>\n\
    <property>\n\
        <name>javax.jdo.option.ConnectionURL</name>\n\
        <value>jdbc:postgresql://postgres:5432/airflow</value>\n\
    </property>\n\
    <property>\n\
        <name>javax.jdo.option.ConnectionDriverName</name>\n\
        <value>org.postgresql.Driver</value>\n\
    </property>\n\
    <property>\n\
        <name>javax.jdo.option.ConnectionUserName</name>\n\
        <value>airflow</value>\n\
    </property>\n\
    <property>\n\
        <name>javax.jdo.option.ConnectionPassword</name>\n\
        <value>airflow</value>\n\
    </property>\n\
    <property>\n\
        <name>fs.s3a.access.key</name>\n\
        <value>admin</value>\n\
    </property>\n\
    <property>\n\
        <name>fs.s3a.secret.key</name>\n\
        <value>password123</value>\n\
    </property>\n\
    <property>\n\
        <name>fs.s3a.endpoint</name>\n\
        <value>http://minio:9000</value>\n\
    </property>\n\
    <property>\n\
        <name>fs.s3a.path.style.access</name>\n\
        <value>true</value>\n\
    </property>\n\
    \n\
    <property>\n\
        <name>fs.s3.impl</name>\n\
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>\n\
    </property>\n\
    <property>\n\
        <name>fs.s3a.impl</name>\n\
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>\n\
    </property>\n\
</configuration>' > /opt/hive/conf/hive-site.xml

# 3. Tạo Script khởi động
RUN echo '#!/bin/bash\n\
echo "Kiểm tra và khởi tạo Database Schema cho Hive..."\n\
/opt/hive/bin/schematool -initSchema -dbType postgres || echo "Schema đã được tạo từ trước."\n\
echo "Khởi động Hive Metastore..."\n\
exec /opt/hive/bin/hive --service metastore\n\
' > /opt/hive/start-metastore.sh
RUN chmod +x /opt/hive/start-metastore.sh

# Đưa quyền điều hành lại cho user mặc định để đảm bảo bảo mật
USER hive

# Ghi đè tiến trình khởi động mặc định
ENTRYPOINT ["/opt/hive/start-metastore.sh"]