FROM apache/airflow:2.9.1-python3.10

USER root

# Cài đặt Java, Curl VÀ bổ sung các công cụ biên dịch (build-essential, python3-dev...) 
# để khắc phục lỗi khi pip install các thư viện C/C++
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        default-jre-headless \
        curl \
        build-essential \
        python3-dev \
        libpq-dev \
        default-libmysqlclient-dev \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Cấu hình JAVA_HOME trỏ về bản Java mặc định của hệ thống
ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow

# Cài đặt Python packages (Lúc này các tool build C/C++ ở trên đã sẵn sàng)
COPY requirements.txt /requirements.txt
# Sửa dòng 26 thành:
RUN pip install --default-timeout=1000 --retries=10 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --no-cache-dir -r /requirements.txt

# ==============================================================================
# TẢI JAR CHO AIRFLOW (Để Airflow đóng vai trò làm Spark Driver mượt mà)
# ==============================================================================
# Đường dẫn mặc định khi pip install pyspark trong Airflow image
ENV AIRFLOW_PYSPARK_JARS=/home/airflow/.local/lib/python3.10/site-packages/pyspark/jars

# Tải các file JAR (Hadoop AWS + Delta Lake + PostgreSQL) trút thẳng vào họng PySpark
RUN curl -o $AIRFLOW_PYSPARK_JARS/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    && curl -o $AIRFLOW_PYSPARK_JARS/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar \
    && curl -o $AIRFLOW_PYSPARK_JARS/postgresql-42.7.3.jar \
    https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar \
    && curl -o $AIRFLOW_PYSPARK_JARS/iceberg-spark-runtime-3.5_2.12-1.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.5.0/iceberg-spark-runtime-3.5_2.12-1.5.0.jar \
    && curl -o $AIRFLOW_PYSPARK_JARS/iceberg-aws-bundle-1.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/1.5.0/iceberg-aws-bundle-1.5.0.jar