FROM python:3.10-bullseye

USER root
# Cài đặt Java 11 (Bản ổn định tuyệt đối cho Spark)
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless curl procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_HOME=/usr/local/lib/python3.10/site-packages/pyspark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# Cài đặt PySpark và các thư viện hỗ trợ (geopandas cho không gian, psycopg2 cho db)
RUN pip install --default-timeout=1000 --retries=10 --no-cache-dir \
    pyspark==3.5.1 \
    h3==3.7.6 \
    great_expectations==0.15.50 \
    geopandas \
    psycopg2-binary \
    pandas \
    prophet \
    pymysql \
    pyarrow

# ==============================================================================
# TẢI CÁC THƯ VIỆN JAR CẦN THIẾT CHO SPARK
# (Vì PySpark 3.5.1 dùng Hadoop 3.3.4, ta phải tải thư viện AWS bản 3.3.4)
# ==============================================================================

# 1. Thư viện để Spark kết nối được với MinIO (S3)
RUN curl -o $SPARK_HOME/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    && curl -o $SPARK_HOME/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar



# Xóa 2 lệnh tải delta-spark và delta-storage
# Thêm lệnh tải Iceberg:
RUN curl -o $SPARK_HOME/jars/iceberg-spark-runtime-3.5_2.12-1.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.5.0/iceberg-spark-runtime-3.5_2.12-1.5.0.jar \
    && curl -o $SPARK_HOME/jars/iceberg-aws-bundle-1.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/1.5.0/iceberg-aws-bundle-1.5.0.jar